# Generated by Django 3.0.7 on 2020-07-02 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200702_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 15, 37, 55, 418594, tzinfo=utc)),
        ),
    ]
